"""Regenerate INDEX.md from the frontmatter of every topic file.

Run after adding or editing a topic:  python build_index.py
Stdlib only; parses the simple frontmatter shape used in _template.md.
"""
import re
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).parent
# Categories whose facts (model IDs, prices, versions) go out of date.
VOLATILE = ("models", "setup", "deployment")
STALE_DAYS = 90
# INDEX.md section order: the entry point first, then the categories in AGENTS.md order.
ORDER = ("scenarios", "concepts", "models", "llm-apps", "ml", "cv", "speech", "setup", "deployment")
SKIP = {"README.md", "AGENTS.md", "CLAUDE.md", "INDEX.md", "ROADMAP.md", "_template.md"}


def links(text):
    """[[wiki-links]] in prose; code is stripped so `[[1, 2]]` lists don't count."""
    prose = re.sub(r"`[^`\n]*`", "", re.sub(r"```.*?```", "", text, flags=re.S))
    return [l.strip() for l in re.findall(r"\[\[([^\]|#]+)", prose)]


def frontmatter(text):
    m = re.match(r"---\n(.*?)\n---", text.replace("\r\n", "\n"), re.S)
    if not m:
        return None
    meta, key = {}, None
    for line in m.group(1).splitlines():
        if line.startswith("  - ") and key:
            meta.setdefault(key, []).append(line[4:].strip().strip('"'))
        elif ":" in line and not line.startswith(" "):
            key, _, val = line.partition(":")
            key, val = key.strip(), val.split("#")[0].strip()
            if val.startswith("["):
                meta[key] = [v.strip() for v in val.strip("[]").split(",") if v.strip()]
            elif val:
                meta[key] = val.strip('"')
    return meta


def stale(meta, rel, today):
    """True for a volatile-category topic whose last_verified is missing, malformed or too old."""
    if rel.split("/")[0] not in VOLATILE:
        return False
    try:
        return date.fromisoformat(meta.get("last_verified", "")) < today - timedelta(days=STALE_DAYS)
    except ValueError:
        return True


def build(today=None):
    today = today or date.today()
    rows, bad, out_links, old, groups = [], [], {}, [], {}
    for path in sorted(ROOT.rglob("*.md")):
        rel = path.relative_to(ROOT).as_posix()
        if path.name in SKIP or rel.startswith("."):
            continue
        text = path.read_text(encoding="utf-8")
        out_links[path.stem] = (rel, links(text))
        meta = frontmatter(text)
        if not meta or "title" not in meta:
            bad.append(rel)
            continue
        if stale(meta, rel, today):
            old.append(f"{rel} ({meta.get('last_verified', 'no date')})")
        uses = meta.get("use_cases", [])
        row = (
            f"| [{meta['title']}]({rel}) | {', '.join(meta.get('tags', []))} "
            f"| {'; '.join(uses[:3])} | {meta.get('status', '?')} |"
        )
        rows.append(row)
        groups.setdefault(meta.get("category", rel.split("/")[0]), []).append(row)
    cats = [c for c in ORDER if c in groups] + sorted(set(groups) - set(ORDER))
    out = [
        "# Index",
        "",
        "Generated by `python build_index.py` - do not edit by hand.",
        f"{len(rows)} topics. Match your task against Tags / Use when, then read the full file.",
        "",
        " | ".join(f"[{c} ({len(groups[c])})](#{c})" for c in cats),
    ]
    for c in cats:
        out += ["", f"## {c}", "", f"{len(groups[c])} topics.", "",
                "| Topic | Tags | Use when | Status |", "|---|---|---|---|", *groups[c]]
    out.append("")
    (ROOT / "INDEX.md").write_text("\n".join(out), encoding="utf-8", newline="\n")
    broken = [f"{rel} -> [[{l}]]" for rel, ls in out_links.values() for l in ls if l not in out_links]
    linked = {l for stem, (_, ls) in out_links.items() for l in ls if l != stem}
    orphans = sorted(rel for stem, (rel, _) in out_links.items() if stem not in linked)
    # Overview = any non-scenario topic that is not a from-scratch walkthrough.
    from_scenarios = {l for rel, ls in out_links.values() if rel.startswith("scenarios/") for l in ls}
    unreached = sorted(rel for stem, (rel, _) in out_links.items()
                       if "/" in rel and not rel.startswith("scenarios/")
                       and "from-scratch" not in stem and stem not in from_scenarios)
    return rows, bad, broken, orphans, old, unreached


if __name__ == "__main__":
    rows, bad, broken, orphans, old, unreached = build()
    print(f"indexed {len(rows)} topics")
    if orphans:
        print(f"warning: {len(orphans)} topic(s) no other topic links to: {orphans}")
    if unreached:
        print(f"warning: {len(unreached)} overview topic(s) no scenarios/ file links to: {unreached}")
    if old:
        print(f"warning: {len(old)} topic(s) in {'/'.join(VOLATILE)} not verified in {STALE_DAYS} days, re-check their sources: {old}")
    if bad or broken:
        raise SystemExit(f"missing/invalid frontmatter: {bad}\nbroken [[links]]: {broken}")
