"""Regenerate INDEX.md from the frontmatter of every topic file.

Run after adding or editing a topic:  python build_index.py
Stdlib only; parses the simple frontmatter shape used in _template.md.
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent
SKIP = {"README.md", "AGENTS.md", "CLAUDE.md", "INDEX.md", "ROADMAP.md", "_template.md"}


def links(text):
    """[[wiki-links]] in prose; code is stripped so `[[1, 2]]` lists don't count."""
    prose = re.sub(r"`[^`\n]*`", "", re.sub(r"```.*?```", "", text, flags=re.S))
    return [l.strip() for l in re.findall(r"\[\[([^\]|#]+)", prose)]


def frontmatter(text):
    m = re.match(r"---\n(.*?)\n---", text.replace("\r\n", "\n"), re.S)
    if not m:
        return None
    meta, key = {}, None
    for line in m.group(1).splitlines():
        if line.startswith("  - ") and key:
            meta.setdefault(key, []).append(line[4:].strip().strip('"'))
        elif ":" in line and not line.startswith(" "):
            key, _, val = line.partition(":")
            key, val = key.strip(), val.split("#")[0].strip()
            if val.startswith("["):
                meta[key] = [v.strip() for v in val.strip("[]").split(",") if v.strip()]
            elif val:
                meta[key] = val.strip('"')
    return meta


def build():
    rows, bad, out_links = [], [], {}
    for path in sorted(ROOT.rglob("*.md")):
        rel = path.relative_to(ROOT).as_posix()
        if path.name in SKIP or rel.startswith("."):
            continue
        text = path.read_text(encoding="utf-8")
        out_links[path.stem] = (rel, links(text))
        meta = frontmatter(text)
        if not meta or "title" not in meta:
            bad.append(rel)
            continue
        uses = meta.get("use_cases", [])
        rows.append(
            f"| [{meta['title']}]({rel}) | {meta.get('category', rel.split('/')[0])} "
            f"| {', '.join(meta.get('tags', []))} | {'; '.join(uses[:3])} "
            f"| {meta.get('status', '?')} |"
        )
    out = [
        "# Index",
        "",
        "Generated by `python build_index.py` - do not edit by hand.",
        f"{len(rows)} topics. Match your task against Tags / Use when, then read the full file.",
        "",
        "| Topic | Category | Tags | Use when | Status |",
        "|---|---|---|---|---|",
        *rows,
        "",
    ]
    (ROOT / "INDEX.md").write_text("\n".join(out), encoding="utf-8", newline="\n")
    broken = [f"{rel} -> [[{l}]]" for rel, ls in out_links.values() for l in ls if l not in out_links]
    linked = {l for stem, (_, ls) in out_links.items() for l in ls if l != stem}
    orphans = sorted(rel for stem, (rel, _) in out_links.items() if stem not in linked)
    return rows, bad, broken, orphans


if __name__ == "__main__":
    rows, bad, broken, orphans = build()
    print(f"indexed {len(rows)} topics")
    if orphans:
        print(f"warning: {len(orphans)} topic(s) no other topic links to: {orphans}")
    if bad or broken:
        raise SystemExit(f"missing/invalid frontmatter: {bad}\nbroken [[links]]: {broken}")
